### ISSUE TITLE
No build on kernel 4.19.1-arch1-1 in ArchLinux

### ISSUE THREAD

**Issue by Genues** [lwfinger/rtl8723au#72]
Hi.
I have problem with build this driver.
`home/noname/aur/rtl8723au/os_dep/os_intfs.c:962:22: error: initialization of «u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))» {aka «short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))»} from incompatible pointer type «u16 (*)(struct net_device *, struct sk_buff *, void *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))» {aka «short unsigned int (*)(struct net_device *, struct sk_buff *, void *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))»} [-Werror=incompatible-pointer-types]
  .ndo_select_queue = rtw_select_queue`
Please help! Thanks.

**Comment by lwfinger** [comment]
Sorry. I missed this repo. The fix was just pushed. Do another 'git pull'.

**Comment by Genues** [comment]
Thank you!
